build.boot, src/oc/lib/api/common.clj, src/oc/lib/db/common.clj, src/oc/lib/db/migrations.clj, src/oc/lib/db/pool.clj, src/oc/lib/hateoas.clj, src/oc/lib/jwt.clj, src/oc/lib/rethinkdb/common.clj, src/oc/lib/schema.clj, test/oc/unit/db/pool.clj
Some of the changes to support `access` branches of API and Auth. Not all of them though, many were done to mainline before release `0.2.4` on Jan. 30.
Changes:
0.2.4 - added HATEOAS `remove` rel link w/ no media-type
0.3.0 - moved oc.lib.api.common from Auth to oc.lib.
0.4.0 - differentiate `accept` and `content-type` in HATEOAS links
0.4.1 - allow `hateoas/delete-link` to accept optional args
0.5.0 - Optional extra HATEOAS link args as a map rather than optional arguments.
0.5.1 - Make extra map optional when using bare `hateoas/link-map` function.
=> Support access branches

build.boot, src/oc/lib/db/common.clj
This adds a group count query needed to efficiently count the # of entries for a board response.
For the PR, you should review the code, but testing is indirect in storage API.
See: https://github.com/open-company/open-company-api/pull/73
=> History count in board response

build.boot, src/oc/lib/sqs.clj
https://trello.com/c/SMInMPRe
To test, follow the steps in `comments` in `oc.lib.sqs` to send a message that causes an unhandled exception in the consumer (replace `replace-me` in the `sqs-queue` var with a real SQS queue name).
In addition to the `println` output from the sample SQS consumer, you should see timbre log output for the error that looks like:
```
17-04-17 11:17:38 Seans-Mac-Pro.local ERROR [oc.lib.sqs:24] -
java.lang.Thread.run                       Thread.java:  745
java.util.concurrent.ThreadPoolExecutor$Worker.run           ThreadPoolExecutor.java:  617
java.util.concurrent.ThreadPoolExecutor.runWorker           ThreadPoolExecutor.java: 1142
...
clojure.core.async.impl.channels.ManyToManyChannel/fn/fn                      channels.clj:   95 …
```
=> Log unhandled exceptions in SQS consumers

project.clj, src/oc/lib/db/common.clj, src/oc/lib/schema.clj, src/oc/lib/slack.clj
Supports: https://github.com/open-company/open-company-interaction/pull/3
Changes to review for:
- Allow a DB resource to be updated w/o providing the original resource map.
- Schema for storing Slack mirror (channel to mirror to) and Slack thread (channel/thread where an entry has been mirrored to)
- Move bot's Slack API into oc.lib since it's now shared between Bot and Interaction services.
=> Phase 3: Slack commenting

README.md, project.clj, src/oc/lib/db/common.clj, src/oc/lib/db/pool.clj, src/oc/lib/proxy/sheets_chart.clj
This PR supports: https://github.com/open-company/open-company-storage/pull/87
This PR changes common DB functions:
- checks for cursor responses and drains them to a seq in all `get-all` and full table functions
- adds a higher arity resources and relations fn that provides the fine control needed for activity timeline
To test:
- Generate 6 months+ of update data with the new storage data generator
- Use the regular storage APIs, no blank API responses in board operations due to cursors? No regressions in normal storage API usage from the UI?
- Use the activity timeline / calendar API from the UI
=> All activity

LICENSE, README.md, project.clj, src/oc/lib/slack.clj
Supports: https://trello.com/c/YBUH0SR6
Quick PR that adds a Slack post of attachments, rather than text.
Will get tested thoroughly w/ Digest PRs
Already deployed to clojars. Just merge.
=> Post slack attachments

project.clj, src/oc/lib/slugify.clj, src/oc/lib/text.clj, test/oc/unit/text.clj
Supports: https://trello.com/c/YBUH0SR6
Add a text processing ns and an attribution function that builds human readable authorship attribution.
At this point this fn is shared by bot and email to attribute comments.
=> Shared attribution fn

project.clj, src/oc/lib/jwt.clj, src/oc/lib/slack.clj
https://trello.com/c/oR339oGj
Supports: https://github.com/open-company/open-company-interaction/pull/15
Use a reply to an original comment message, rather than a reply link to get the comment thread going. This works around the need to create our own URL to the thread. Slack does it for us.
Also open JWT claims up for extension so we won't be forced to migrate all JWT verifying services in lock step if the claims expand in the future.
Follow testing instructions in Interaction PR.
This is already on Clojars and there is no deployment step, so just a merge.
=> New slack comment thread scheme

project.clj, src/oc/lib/slack.clj
https://trello.com/c/DG4A0YwJ
This PR supports: https://github.com/open-company/open-company-bot/pull/22
Echoing from Slack back into Carrot was broken with `0.16.0` as we ended up returning the child message rather than the parent in the new reply scheme, which means the thread lookup on inbound Slack messages always failed.
This fixes the return of echo and proxy so they return the initial message, not the reply. The timestamp of the return is stored by interaction services for thread lookup.
In addition, this PR adds the invisible Unicode marker to messages we send to Slack with the `post-message` fn which is used directly in some places, this brings it inline with `post-message` and `echo-message`.
=> Fix Slack -> Carrot comments

project.clj, src/oc/lib/async/watcher.clj
This change uses the non-blocking, aka parking async channel reader.
It also supports the ability to unwatch all watches by the client id.  This is useful so that the client doesn't have to keep track of all their watches and can remove all on disconnect or if they want to "clear" all watches.
The watchers hashmap now contains a client id key used to lookup all the client's watches.
This can be tested with the steps seen here https://github.com/open-company/open-company-web/pull/395
=> Allow a single client id to unwatch all watches.

project.clj
Version 0.16.4 wasn't deployed to clojars just yet. To run locally use:
`lein install`
to run it on staging or beta use
`lein deploy release`
follow the instructions in README for more info.
=> Email personal notes

project.clj, src/oc/lib/jwt.clj, src/oc/lib/slack.clj
Support for unfurl in the Slack API.
Also trust the new service "super-user" token for internal service requests.
This has already been deployed to clojars as version 0.16.5
This can be tested with the slack router since it uses this version.
=> Unfurl slack url

project.clj, src/oc/lib/jwt.clj, src/oc/lib/schema.clj
Supports: https://github.com/open-company/open-company-auth/pull/50
NB: After finishing the review of the auth PR, you need to update the version here to `0.16.12` and do a `lein deploy release`, then update the Auth, Storage and Interaction branches to use `0.16.12` and deploy all 3 to beta at the same time.
NB: If this goes out BEFORE https://github.com/open-company/open-company-lib/pull/33 (which is `0.16.11` then you need to add a note to https://github.com/open-company/open-company-lib/pull/33 that it needs to merge this and go to version `0.16.13` for the Google work.
If this goes out AFTER https://github.com/open-company/open-company-lib/pull/33 then you only need to ensure that's been merged in cleanly into this.
=> Slack names

project.clj, src/oc/lib/db/migrations.clj
Adds a remove index option to support the revised NUX work.
To test:
=> Add `remove-index` to migration helpers.

project.clj, src/oc/lib/db/common.clj
This adds support for the not equals operator in the query filter maps.
After testing , remove the alpha and run `lein deploy release`.
=> Support for not equals database operation.

project.clj, src/oc/lib/text.clj, test/oc/unit/text.clj
We had a bug in the xss strip function that was stripping out all the HTML markup, not only script, style and input elements.
```
dev=> (str/strip-xss-tags "<script and something here>Hello</script><style>Style</style><input and=\"soon\"><span but-this=\"\">Will be in</span>")
"HelloStyleWill be in"
```
This should fix that.
Since i changed only this line, the rest of the PRs are only to upgrade lib it should be enough to test the function directly in repl and make sure it removes only the needed tags.
Test the function with tags like:
- `a`, `br`, `span`, `div`, `script`, `style` and `input` and any other you can think of (mostly test weird syntax situations
- test opening tags (like `<style>`)
- test auto closing tags (like `<input />`)
- test closing tags (like `</ style>`)
- test …
=> Fix xss strip

project.clj, src/oc/lib/slack.clj
Before this change we were not able to send message text along with attachments.  This change allows for that to happen.
=> Pass in text with attachments

project.clj, src/oc/lib/slugify.clj, test/oc/unit/slugify.clj
[Trello](https://trello.com/c/tkAqzSdx)
User used `Ημερολόγιο` as section name which slugified to nothing and broke the world.
Requires: https://github.com/open-company/open-company-storage/pull/175
To test:
- Run the storage branch mentioned above
- Create a new org named `Ημερολόγιο`
- Create a new section in the org named `Ημερολόγιο`
- Update the release version to drop the alpha in both lib and storage
- Release the lib to clojars
- Merge
- Deploy
=> Fix slugify issue when slug is sanitized to nothing. Test for the same.

project.clj, src/oc/lib/api/common.clj
Use the proper function to decode the id-token to support old and new token formats.
Related PRs:
- [Storage](https://github.com/open-company/open-company-storage/pull/180)
- [Auth](https://github.com/open-company/open-company-auth/pull/72)
- [Interaction](https://github.com/open-company/open-company-interaction/pull/28)
To test:
- get an old token that has `:team-id` instead of `:teams` in it
- load a secure post url with that token
- no errors? Good
- update lib
- release lib
- merge and deploy
=> Fix decode id-token

README.md, project.clj, src/oc/lib/jwt.clj
This change fixes and issue where an invalid token can be used successfully.
To test:
- generate a token to be used in the tests
Run the commands in the console.  In the last test you will remove one or more characters from the token.  Before this function would return true.
```
dev=> (require '[oc.lib.jwt :as jwt])
nil
dev=> (require '[oc.storage.config :as config])
nil
dev=> (jwt/check-token "<generated-token>" config/passphrase)
true
dev=> (jwt/check-token "<generated-token-minus-a-character-or-more" config/passphrase)
```
After releasing the new lib make sure to merge in the other PRs mentioned below.
=> Return value of verify function.

project.clj, src/oc/lib/sqs.clj
This change supports reading from S3.  If an event message shows up in the SQS queue and it is from S3, this code will read that data.  This will allow us to write to a kinesis firehouse, send each record to s3 and then read large amounts of data from s3.
=> Kinesis s3 sns

project.clj, src/oc/lib/async/watcher.clj, src/oc/lib/middleware/wrap_ensure_origin.clj, src/oc/lib/storage.clj
Card: https://trello.com/c/Il0A8Xbh
Needs:
- [Notify](https://github.com/open-company/open-company-notify/pull/11)
- [Interaction](https://github.com/open-company/open-company-interaction/pull/31)
- [Change](https://github.com/open-company/open-company-change/pull/15)
- [Infrastructure](https://github.com/belucid/open-company-infrastructure/pull/101)
I had to downgrade http-kit since Sente doesn't support the latest version: the latest change removed the support for the server sending messages to the client before the handshake, this feature is needed by Sente.
I also had to downgrade Sente since the latest version wasn't working w/o the CSRF token check, i tried following their docs but no luck, not sure if i am missing something or their doc is lacking, i didn't want to spend more time …
=> Fix lib WS 403

project.clj, src/oc/lib/jwt.clj, src/oc/lib/schema.clj
We have a common `author-for-user` fn that makes an author out of a JWT user, but we often need to do the same from a DB user. This doesn't work on the current fn because a JWT user has a `name` prop, and an author has a `name` prop, but a DB user only has `first_name` and `last_name` props. 
Elsewhere in the common code, we have a fn to derive a `name` from the other 2, but it wasn't being used in `author-for-user` making the fn only useful for transforming JWT users. This just refactors that stuff in a backwards compatible way, and updates the fn to be useful for transforming DB users into authors.
To test:
- Open a support REPL (latest mainline uses this alpha release)
- Get a JWT token parsed into a map
- Call `lib-schema/author-for-user` on the map
- Get a DB user with something like …
=> Make author-for-user more flexible

project.clj, src/oc/lib/middleware/wrap_ensure_origin.clj
To test:
- Change service is running `0.17.2-alpha1` on staging
- Pretend like your are an out-of-browser HTTP client like NodePing with `curl -i https://staging-change.carrot.io/ping`
- Now pretend like you are a Websocket client w/o our orign with wscat with something like `wscat --connect "wss://staging-change.carrot.io/change-socket/user/1234-1234-1234?user-id=1234&client-id=1234"`
To release:
- Delete change service branch `0.17.2-alpha`
- Mainline/master update of oc.lib to 0.17.2 and deploy on
=> Only check origin on websocket connections.

project.clj, src/oc/lib/html.cljc
Card: https://trello.com/c/dO56dk9F
Related PRs:
- [Web](https://github.com/open-company/open-company-web/pull/842)
- [Bot](https://github.com/open-company/open-company-bot/pull/79)
To test:
- add some text posts
- add some text+image posts
- add some text+video posts
- add some text+videos+images mixed posts
- go to all posts
- send yourself a Slack digest
- now share a post with a thumbnail in Slack from Carrot
=> Block kit accessory

project.clj, src/oc/lib/oauth.cljc
Review with:
- Auth: https://github.com/open-company/open-company-auth/pull/91
- Web: https://github.com/open-company/open-company-web/pull/1032
To test:
- Onboard user with Slack
- Onboard user with Google
- Invite an email user
- Add the Slack bot
- Invite a Slack user
- Share a post requiring authentication, open it in incognito browser, hit the login wall
- Try logging in using any other method that I haven't thought of...
=> Decode :redirect key from oauth state string if present

project.clj, src/oc/lib/db/common.clj
This just fixes a small bug in 1 arity variant of a DB function where we used `with-fields` rather than `pluck`. `pluck` was used in the other variants. The difference is `pluck` allows docs/rows with nil/no key on that field whereas `with-fields` filters those out. Was never intended to filter them out in this db fn.
Fix was used in support, so no direct consuming PR.
=> Normalize read resource

project.clj, src/oc/lib/slack.clj
FIx pagination when the organization has more channels than our current pagination batch.
To test:
- change `oc.auth.lib.slack` line 364 to be `(slack-lib/get-channels bot-token {:limit 10})`. This will force a smaller pagination of the channels list for testing purpose
- restart your local auth server to make sure
- now sign in/up with Carrot org
- add a topic
- fill a name and description for the new section
- add a mirror channel
- do you see all the channels in the channels list? (pagination is usually 3k, but we changed it to 10 so it should be easy to check if pagination works)
- do you see all type of channels? IM, MPIM, private and public?
- select one of your IM or MPIM channels: this is to make sure the bot joins the channel, otherwise it won't be able to send messages in there …
=> Fix slack channels
