build.boot, src/oc/lib/proxy/sheets_chart.clj
Card: https://trello.com/c/ZWMu5BHt
Follow the steps in the main Web PR https://github.com/open-company/open-company-web/pull/238
=> Sheet proxy

build.boot, src/oc/lib/db/migrations.clj
Changes for DB migrations to support: https://github.com/open-company/open-company-api/pull/77
=> Entry uuid

build.boot, src/oc/lib/schema.clj
oc.lib repo changes to support: https://github.com/open-company/open-company-api/pull/78
=> Interactions

project.clj, src/oc/lib/jwt.clj
Main PR: https://github.com/open-company/open-company-web/pull/244
=> Base ML UI

project.clj, src/oc/lib/proxy/sheets_chart.clj
Main PR: https://github.com/open-company/open-company-web/pull/249
=> Media handling

README.md, project.clj, src/oc/lib/db/common.clj
This PR provides a new DB function, used by https://github.com/open-company/open-company-storage/pull/99
This function, generally, will return the n most common x's from any table. Specifically we're using it to return the most reactions for users and orgs in the notion of "favorite reactions".
=> New reactions

project.clj, src/oc/lib/db/common.clj, src/oc/lib/db/migrations.clj
Test with https://github.com/open-company/open-company-storage/pull/130
=> Count option and must read as option.

project.clj, src/oc/lib/jwt.clj, src/oc/lib/schema.clj
See https://github.com/open-company/open-company-web/pull/586 for test steps.
=> New jwt tokens for google sso

project.clj, src/oc/lib/api/common.clj
Main PR: https://github.com/open-company/open-company-storage/pull/168
Once merged do the usual dance:
- remove alpha from version
- deploy version to clojar
- increase the version and add alpha
=> Fix duplicated share

project.clj
Main PR https://github.com/open-company/open-company-change/pull/11
=> Fix change TTL

project.clj, src/oc/lib/api/common.clj, src/oc/lib/jwt.clj
Main PR: https://github.com/open-company/open-company-digest/pull/11
Testing steps are in the Main PR.
After testing this:
=> Generate and decode a token that can be used to identify a user.

project.clj, src/oc/lib/api/common.clj, src/oc/lib/jwt.clj
Main PR: https://github.com/open-company/open-company-web/pull/762
=> Post link behaviour

project.clj, src/oc/lib/dynamo/common.clj
Main PR: https://github.com/open-company/open-company-notify/pull/4
=> Fix Notify ttl

project.clj, src/oc/lib/text.clj
Needed by https://github.com/open-company/open-company-email/pull/44
=> Digest design

project.clj, src/oc/lib/change.clj
This change adds the ability to query seen/read data from the change service.
Test steps here https://github.com/open-company/open-company-bot/pull/64
After merge you will need to change the version info and release a new clojars lib.
=> Functions to access data from the Change service.

project.clj, src/oc/lib/slack.clj, src/oc/lib/user_avatar.clj
Main PR https://github.com/open-company/open-company-bot/pull/77
=> Block kit digest

.travis.yml, project.clj, src/oc/lib/html.cljc
Main PR: https://github.com/open-company/open-company-web/pull/860
=> Gif picker

project.clj, src/oc/lib/schema.clj
Card: https://trello.com/c/9m4ZQpnb/2051-wst-updates-backend
Linked PR: https://github.com/open-company/open-company-web/pull/880
=> WST updates

project.clj, src/oc/lib/db/common.clj
Main PR: https://github.com/open-company/open-company-web/pull/911
=> Post sorting

project.clj, src/oc/lib/jwt.clj, src/oc/lib/schema.clj, src/oc/lib/user.cljc
Main PR: https://github.com/open-company/open-company-digest/pull/24
=> Digest stripped down

project.clj, src/oc/lib/jwt.clj, src/oc/lib/schema.clj, src/oc/lib/user.cljc
Review with https://github.com/open-company/open-company-web/pull/932
Update version to drop alpha. Release to clojars.
=> Follow ups

project.clj, src/oc/lib/lambda/common.clj
Trello: https://trello.com/c/Vn56Ry3Q/2160-mobile-push-notifications
Parent PR: https://github.com/open-company/open-company-web/pull/979
=> Mobile push notifications

project.clj, src/oc/lib/oauth.cljc
Linked PR: https://github.com/open-company/open-company-web/pull/924
=> Move oauth state encoding/decoding utility functions into shared CLJC file

project.clj, src/oc/lib/async/watcher.clj
Supports https://github.com/open-company/open-company-web/pull/1002
=> Performance improvement

project.clj, src/oc/lib/slack.clj, src/oc/lib/storage.clj
Main PR: https://github.com/open-company/open-company-auth/pull/92
=> Better bot removal

project.clj
Main PR: https://github.com/open-company/open-company-web/pull/1071
=> ClojureScript upgrade

project.clj, src/oc/lib/api/common.clj
Main PR: https://github.com/open-company/open-company-web/pull/1092
=> Autosave sync

project.clj, src/oc/lib/html.cljc
Main PR: https://github.com/open-company/open-company-web/pull/1137
=> Code blocks

project.clj, src/oc/lib/user.cljc, test/oc/unit/user.clj
Main PR: https://github.com/open-company/open-company-web/pull/1150
=> People profiles

project.clj, src/oc/lib/dynamo/common.clj
Main PR: https://github.com/open-company/open-company-auth/pull/111
=> Invite throttle

project.clj, src/oc/lib/api/common.clj, src/oc/lib/dynamo/common.clj
Main PR: https://github.com/open-company/open-company-auth/pull/112
=> Recipient validation
